using System;

namespace UL.Aria.Service.Contracts.Dto
{
	/// <summary>
	/// Class OutboundDocumentDto. POCO, json serialized so no data contract attributes.
	/// </summary>
	public class OutboundDocumentDto
	{
		/// <summary>
		/// Gets or sets the message identifier.
		/// </summary>
		/// <value>The message identifier, blob name, generated by the JMS listener and test harness.</value>
		public string MessageId { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether this <see cref="OutboundDocumentDto"/> is new.
		/// </summary>
		/// <value><c>true</c> if new; otherwise, <c>false</c>.</value>
		public bool IsNew { get; set; }

		/// <summary>
		/// Gets or sets the type of the content.
		/// </summary>
		/// <value>The type of the content.</value>
		public string ContentType { get; set; }

		/// <summary>
		/// Gets or sets the document identifier.
		/// </summary>
		/// <value>The document identifier.</value>
		public Guid DocumentId { get; set; }

		/// <summary>
		/// Gets or sets the primary search entity identifier.
		/// </summary>
		/// <value>The primary search entity identifier.</value>
		public Guid PrimarySearchEntityId { get; set; }

		/// <summary>
		/// Gets or sets the name of the original file.
		/// </summary>
		/// <value>The name of the original file.</value>
		public string OriginalFileName { get; set; }

		/// <summary>
		///     Gets or sets the title.
		/// </summary>
		/// <value>
		///     The title.
		/// </value>        
		public string Title { get; set; }

		/// <summary>
		/// Gets or sets the description.
		/// </summary>
		/// <value>The description.</value>
		public string Description { get; set; }

		/// <summary>
		/// Gets or sets the document type identifier.
		/// </summary>
		/// <value>The document type identifier.</value>
		public Guid? DocumentTypeId { get; set; }

		/// <summary>
		/// Gets or sets the permission.
		/// </summary>
		/// <value>The permission.</value>
		public DocumentPermissionEnumDto Permission { get; set; }

		/// <summary>
		/// Gets or sets the size.
		/// </summary>
		/// <value>The size.</value>
		public long Size { get; set; }

		/// <summary>
		/// Gets or sets the last modified by.
		/// </summary>
		/// <value>The last modified by.</value>
		public string LastModifiedBy { get; set; }

		/// <summary>
		/// Gets or sets the hash value.
		/// </summary>
		/// <value>The hash value.</value>
		public string HashValue { get; set; }
	}
}